# Generated by Django 5.1.15 on 2026-09-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ena', 'ENA (Electric Network Armenia)'), ('veolia_web', 'Veolia — website'), ('veolia_telegram', 'Veolia — Telegram channel'), ('gazprom', 'Gazprom Armenia (reserved, not implemented)')], db_index=True, max_length=32)),
                ('source_type', models.CharField(choices=[('html', 'HTML page'), ('telegram_text', 'Telegram channel preview page')], max_length=32)),
                ('reference', models.CharField(max_length=1024)),
                ('content', models.TextField(blank=True, default='')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fetch_status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('dump_file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('processed', models.BooleanField(db_index=True, default=False, help_text="Reserved for Phase 1's raw→structured parser. Not used in Phase 0.5.")),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['provider', 'fetched_at'], name='ingestion_r_provide_2f918b_idx'), models.Index(fields=['provider', 'processed'], name='ingestion_r_provide_9c33b6_idx')],
            },
        ),
    ]
