# Generated by Django 5.2.17 on 2026-09-11 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutageAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ena', 'ENA (Electric Network Armenia)'), ('veolia_web', 'Veolia — website'), ('veolia_telegram', 'Veolia — Telegram channel'), ('gazprom', 'Gazprom Armenia (reserved, not implemented)')], db_index=True, max_length=32)),
                ('outage_type', models.CharField(choices=[('planned', 'Planned'), ('emergency', 'Emergency')], max_length=16)),
                ('is_preliminary', models.BooleanField(default=False)),
                ('marz', models.CharField(blank=True, max_length=128, null=True)),
                ('district_or_city', models.CharField(blank=True, max_length=128, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('raw_heading_text', models.TextField(blank=True, default='')),
                ('raw_address_text', models.TextField(blank=True, default='')),
                ('external_ref', models.CharField(max_length=128)),
                ('parse_status', models.CharField(choices=[('ok', 'OK'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=16)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('first_seen_raw_content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestion.rawcontent')),
            ],
        ),
        migrations.CreateModel(
            name='OutageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_fragment', models.TextField()),
                ('kind', models.CharField(choices=[('whole_area', 'Whole Area'), ('whole_street', 'Whole Street'), ('street_range', 'Street Range'), ('street_number_range', 'Street Number Range'), ('unparsed', 'Unparsed')], max_length=32)),
                ('street', models.CharField(blank=True, max_length=256, null=True)),
                ('house_low', models.IntegerField(blank=True, null=True)),
                ('house_low_sub', models.CharField(blank=True, max_length=8, null=True)),
                ('house_high', models.IntegerField(blank=True, null=True)),
                ('house_high_sub', models.CharField(blank=True, max_length=8, null=True)),
                ('parity', models.CharField(choices=[('any', 'Any'), ('odd', 'Odd'), ('even', 'Even')], default='any', max_length=8)),
                ('is_matchable', models.BooleanField(default=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='processing.outageannouncement')),
            ],
        ),
        migrations.AddIndex(
            model_name='outageannouncement',
            index=models.Index(fields=['provider', 'starts_at'], name='processing__provide_8d41bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='outageannouncement',
            constraint=models.UniqueConstraint(fields=('provider', 'external_ref'), name='unique_provider_external_ref'),
        ),
        migrations.AddIndex(
            model_name='outagelocation',
            index=models.Index(fields=['street'], name='processing__street_fc92ed_idx'),
        ),
    ]
