# Generated by Django 5.2.17 on 2026-09-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='outageannouncement',
            index=models.Index(fields=['marz', 'ends_at'], name='processing__marz_63b95b_idx'),
        ),
    ]
