# Generated by Django 5.2.17 on 2026-09-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_outageannouncement_processing__marz_63b95b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='outagelocation',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='outagelocation',
            name='qualifier',
            field=models.CharField(blank=True, choices=[('partial', 'Partial'), ('entire', 'Entire')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='outagelocation',
            name='kind',
            field=models.CharField(choices=[('whole_area', 'Whole Area'), ('whole_street', 'Whole Street'), ('street_range', 'Street Range'), ('street_number_range', 'Street Number Range'), ('non_address', 'Non Address'), ('unparsed', 'Unparsed')], max_length=32),
        ),
    ]
