# Generated by Django 5.2.17 on 2026-09-12 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], default='telegram', max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'external_id'), name='unique_channel_external_id')],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('yerevan', 'Yerevan'), ('ararat', 'Ararat')], max_length=32)),
                ('district_or_city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.PositiveIntegerField()),
                ('house_number_sub', models.CharField(blank=True, default='', max_length=16)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.user')),
            ],
        ),
    ]
