# Generated by Django 5.2.17 on 2026-09-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='match_confidence',
            field=models.CharField(blank=True, choices=[('full_address', 'Street and house number matched'), ('street_only', 'Street name only, no house number check')], default='', max_length=16),
        ),
    ]
